In [2]:
import numpy as np

In [3]:
lst = [1,2,3,4,5]

In [4]:
np.array(lst)

array([1, 2, 3, 4, 5])

In [5]:
mat = [
    [1,2,3],
    [4,5,6],
    [7,8,9],
]
       
     

In [6]:
np.array(mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [10]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [12]:
np.ones(3)

array([1., 1., 1.])

In [13]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
np.linspace(1,11,3)

array([ 1.,  6., 11.])

In [15]:
np.linspace(1,11,25)

array([ 1.        ,  1.41666667,  1.83333333,  2.25      ,  2.66666667,
        3.08333333,  3.5       ,  3.91666667,  4.33333333,  4.75      ,
        5.16666667,  5.58333333,  6.        ,  6.41666667,  6.83333333,
        7.25      ,  7.66666667,  8.08333333,  8.5       ,  8.91666667,
        9.33333333,  9.75      , 10.16666667, 10.58333333, 11.        ])

In [16]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [17]:
np.random.rand(4)

array([0.56205663, 0.35038957, 0.63077104, 0.14601024])

In [18]:
np.random.rand(5,5)

array([[0.26581569, 0.69038831, 0.19955927, 0.43265756, 0.71669863],
       [0.73189383, 0.69528751, 0.92980647, 0.84044175, 0.57991168],
       [0.58692528, 0.81799382, 0.32052148, 0.60189182, 0.8587167 ],
       [0.70683734, 0.36094885, 0.96072487, 0.25947633, 0.55916716],
       [0.76842622, 0.08035093, 0.74000775, 0.85874789, 0.92013542]])

In [19]:
np.random.rand(5,5)

array([[0.50652759, 0.73150606, 0.31292895, 0.96813328, 0.07854317],
       [0.65578295, 0.20975977, 0.33395989, 0.78414566, 0.39296142],
       [0.0660416 , 0.39535257, 0.53061044, 0.24120886, 0.00520422],
       [0.56017826, 0.78495219, 0.85666921, 0.48048538, 0.7908654 ],
       [0.67506725, 0.85508044, 0.85482556, 0.54592384, 0.90692102]])

In [21]:
np.random.randn(6,6)

array([[-0.89926834, -0.5306937 , -0.31299606,  0.96160851,  0.37608265,
        -0.42446782],
       [-0.04080654,  0.65269936, -0.54726533, -1.52404243,  0.32584581,
         0.41959322],
       [ 0.5170993 ,  1.6739102 , -1.44370033, -1.07141768, -0.82324187,
         0.4630986 ],
       [ 0.10773776, -0.41377213,  0.22341191,  1.4686961 ,  0.06474206,
         0.71150173],
       [-0.28443532,  0.54290802,  0.11734273,  0.63288529, -0.37776963,
        -0.2840626 ],
       [-0.59963217, -0.49476336,  0.45302611,  0.27115183,  1.50422296,
         0.23505482]])

In [31]:
np.random.randint(1,6)

2

In [32]:
np.random.randint(1,6,10)

array([5, 5, 5, 3, 3, 3, 1, 2, 5, 2])

In [34]:
a = np.arange(25)

In [35]:
r = np.random.randint(0,50,10)

In [36]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [37]:
r

array([18, 19, 26, 11, 33, 39, 23, 40, 27, 44])

In [41]:
a.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [44]:
r.max()

44

In [45]:
r.min()

11

In [47]:
r.argmin()

3

In [49]:
a.shape

(25,)

In [53]:
a.reshape(25,1).shape

(25, 1)

In [51]:
a.shape

(25,)

In [54]:
a.dtype

dtype('int32')

In [47]:
 a= np.arange(11)

In [29]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
a[2]

2

In [35]:
a[:5]

array([0, 1, 2, 3, 4])

In [36]:
a[0:5] = 1000

In [39]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
s = a[0:5]

In [42]:
s

array([0, 1, 2, 3, 4])

In [43]:
s[:] = 777

In [44]:
s

array([777, 777, 777, 777, 777])

In [45]:
a

array([777, 777, 777, 777, 777,   5,   6,   7,   8,   9,  10])

In [48]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
s = a[0:5].copy()

In [55]:
s

array([0, 1, 2, 3, 4])

In [56]:
s[:]= 333

In [57]:
s

array([333, 333, 333, 333, 333])

In [58]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [59]:
mat2 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
    
                ])

In [61]:
mat2.shape

(3, 3)

In [62]:
mat2[1]

array([4, 5, 6])

In [63]:
mat2[1][1]

5

In [65]:
mat2[1,1]

5

In [66]:
mat2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [67]:
mat2[1:,1:]

array([[5, 6],
       [8, 9]])

In [68]:
mat2[1:,:]

array([[4, 5, 6],
       [7, 8, 9]])

In [71]:
b = np.arange(1,11)

In [72]:
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [73]:
b > 2

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True])

In [74]:
b[b>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [76]:
b[b == 2]

array([2])

In [84]:
c = np.arange(0,11)

In [81]:
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [82]:
c + c 

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [83]:
c * c

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [85]:
c/c

C:\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [86]:
1/c

C:\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [87]:
c ** 3

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000],
      dtype=int32)

In [88]:
np.sqrt(c)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [89]:
np.exp(c)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [90]:
np.max(c)

10

In [91]:
np.log(c)

C:\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [93]:
mat2 * mat2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [94]:
import numpy as np

In [95]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [97]:
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [99]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [100]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [101]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [103]:
np.random.rand(1)

array([0.98315429])

In [104]:
np.random.randn(25)

array([-0.63228684,  0.57888334,  0.77572619, -0.78865109, -1.3484942 ,
        0.58887099,  0.6957098 , -2.16313581,  0.96088775,  1.2897701 ,
       -1.71999866, -0.33804154, -0.04770642,  0.45600466,  0.30856647,
        1.28816104, -0.27522468,  0.46751598, -0.18182544,  0.76487944,
       -1.25180263,  1.19860488,  0.56900326, -0.69683648, -1.66999257])

In [108]:
np.arange(1,101) / 100

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])

In [109]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [110]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [111]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [112]:
mat[3,4]

20

In [115]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [118]:
mat[3:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [119]:
mat.sum()

325

In [120]:
mat.std()

7.211102550927978

In [124]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])